version: '2'



services:

  mongo:

    image: mongo:3.4-jessie

    ports:

      - 27017:27017

    expose:

      - 27017

    container_name: mongo

    network_mode: host

  eureka_server:

    build: eureka_server/

    restart: always

    network_mode: "host"

    hostname: localhost

    ports:

      - 8761:8761



  config_server:

    build: config_server/

    restart: always

    network_mode: "host"

    image: demo-config-service

    hostname: localhost

    ports:

      - 8888:8888



  zuul-apigateway:

    build: zulImplementation/

    depends_on:

      - config_server

      - eureka_server

      - music-api

    restart: always

    network_mode: "host"

    hostname: localhost

    ports:

      - 8082:8082



  music-api:

    build: music-api/

    restart: always

    network_mode: "host"

    hostname: localhost

    ports:

      - 8098:8098

    depends_on:

      - config_server

      - eureka_server

  user-services:

    build: user-services/

    restart: always

    network_mode: "host"

    hostname: localhost

    ports:

      - 9098:9098

    depends_on:

      - config_server

      - eureka_server